### ISSUE TITLE
ctrl + alt + O stopped working on FF51

### ISSUE THREAD

**Issue by mzso** [trlkly/dorando-keyconfig#8] opened 2016-09-12 11:04 UTC
Hi!

I'm testing FF51 and this shortcut does not function anymore.

**Comment by trlkly** [comment] 2016-10-09 10:55
This is caused by Issue #9. Closing in lieu of that one. 

(DUPLICATE by Mozilla's naming)

**Closed by trlkly** 2016-10-09 10:55 UTC
